# Generated by Django 3.1.7 on 2021-02-25 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminProfile',
        ),
    ]
