# Generated by Django 3.1.7 on 2021-03-01 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_delete_adminprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='patients',
        ),
        migrations.AddField(
            model_name='appointment',
            name='address',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='appointment',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='appointment',
            name='first_name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='appointment',
            name='last_name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='appointment',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='app_date',
            field=models.DateField(verbose_name='appointment date(mm/dd/yyyy)'),
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
