# Generated by Django 3.1.7 on 2021-03-01 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_auto_20210301_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='app_day',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
