# Generated by Django 3.1.7 on 2021-03-02 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_schedule_app_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='doctors',
        ),
        migrations.AddField(
            model_name='schedule',
            name='status',
            field=models.CharField(choices=[('taken', 'taken'), ('available', 'available')], default='available', max_length=30),
        ),
    ]
