# Generated by Django 3.1.7 on 2021-03-02 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_auto_20210302_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('checkedin', 'checked_in'), ('unchecked', 'unchecked')], default='unchecked', max_length=30),
        ),
    ]
